spring:
  application:
    name: worker
  datasource:
    url: jdbc:mysql://localhost:3306/dadamda?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useCursorFetch=true&defaultFetchSize=1000
    username: root
    password: root
server:
  port: 9000

csv:
  export-path: ./csv/